name: "build-dcevm on push"

on: push

jobs:
  dcevm:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, macos-10.15, windows-2019]
        javaToBuild: [jdk11u]
    steps:
    - uses: actions/checkout@v1
    - uses: liuzhengyang/action-build-dcevm@v2
      id: buildJDK
      with:
        impl: dcevm
        javaToBuild: ${{ matrix.javaToBuild}}
        dcevm_branch: 'dcevm11-jdk-11.0.15-adoptium'
        dcevm_tag: 'dcevm-11.0.15+1'
    - run: ${{ steps.buildJDK.outputs.BuildJDKDir }}/bin/java -version
    - uses: actions/upload-artifact@v2
      with:
        name: '${{ steps.buildJDK.outputs.JdkPackageFileName }}'
        path: ${{ github.workspace }}/temurin-build-dcevm/workspace/artifacts/${{ steps.buildJDK.outputs.JdkPackageFileName }}
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: ${{ github.workspace }}/temurin-build-dcevm/workspace/artifacts/${{ steps.buildJDK.outputs.JdkPackageFileName }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}        
